import torch
import networkx as nx
import numpy as np
import random

class QAPGenerator:
    def __init__(self, problem_size=20, D_type="random", F_type="erdos", **kwargs):
        self.problem_size = problem_size
        self.D_type = D_type
        self.F_type = F_type
        self.p_erdos = kwargs.get("p_erdos", 0.7)
        self.k_max = kwargs.get("k_max", 5)
        self.p_in = kwargs.get("p_in", 0.7)
        self.p_out = kwargs.get("p_out", 0.3)

    def generate(self, batch_size):
        """
        Generate a random Quadratic Assignment Problem (QAP) instance.
        """
        D = self.D_matrix(batch_size, self.problem_size, self.D_type)
        F = self.F_matrix(batch_size, self.problem_size, self.F_type)
        return D, F
    
    def D_matrix(self, batch_size, n, D_type):
        if D_type == "2d_euc":
            D = self.D_2d_euc(batch_size, n)
        elif D_type == "random":
            D = self.D_random(batch_size, n)
        elif D_type == "2d_man":
            D = self.D_2d_man(batch_size, n)

        return D
    
    def F_matrix(self, batch_size, n, F_type):
        if F_type == "random":
            F = self.F_random(batch_size, n)
        elif F_type == "erdos":
            F = self.F_erdos(batch_size, n, self.p_erdos)
        elif F_type == "tree":
            F = self.F_tree(batch_size, n)
        elif F_type == "cluster":
            F = self.F_cluster(batch_size, n, self.p_in, self.p_out, self.k_max)
        return F
    

    ## 2D Euclidean distance
    def D_2d_euc(self, batch_size, n):
        loc = torch.rand(batch_size, n, 2)
        diff = loc.unsqueeze(1) - loc.unsqueeze(2)
        D = torch.sqrt(torch.sum(diff ** 2, dim=-1))
        return D
    
    ## random symmetric matrix D
    def D_random(self, batch_size, n):
        random_matrices = torch.rand(batch_size, n, n)
        D_upper = torch.triu(random_matrices, diagonal=1)
        D = D_upper + D_upper.transpose(-2, -1)
        return D
    
    ## 2D Manhattan distance
    def D_2d_man(self, batch_size, n):
        loc = torch.rand(batch_size, n, 2)
        diff = loc.unsqueeze(1) - loc.unsqueeze(2)
        D = torch.sum(torch.abs(diff), dim=-1)
        return D
    

    ## random symmetric matrix F
    def F_random(self, batch_size, n):
        random_matrices = torch.rand(batch_size, n, n)
        F_upper = torch.triu(random_matrices, diagonal=1)
        F = F_upper + F_upper.transpose(-2, -1)
        return F
    
    ## random F matrix generated by Erdos-Renyi model
    def F_erdos(self, batch_size, n, p=0.7):
        """
        Generate random graph using Erdos-Renyi model where each pair of nodes is connected independently with probability p.
        """
        rand_matrix = torch.rand(batch_size, n, n)
        adj = (rand_matrix < p).float()
        adj_upper = torch.triu(adj, diagonal=1)
        adj_symmetric = adj_upper + adj_upper.transpose(-2, -1)
        weights = torch.rand(batch_size, n, n)
        weights_upper = torch.triu(weights, diagonal=1)
        weights_symmetric = weights_upper + weights_upper.transpose(-2, -1)
        F = adj_symmetric * weights_symmetric
        return F
    
    ## random F matrix generated by Tree model
    def F_tree(self, batch_size, n):
        batch_matrices = []
        for i in range(batch_size):
            G = nx.random_tree(n)
            for u, v in G.edges:
                G[u][v]['weight'] = np.random.uniform(0, 1)
            F = nx.to_numpy_array(G)
            batch_matrices.append(F)
        F_batch = torch.from_numpy(np.array(batch_matrices)).float()
        return F_batch

    ## random F matrix generated by Stochastic Block Model
    def F_cluster(self, batch_size, n, p_in=0.7, p_out=0.3, k_max=5):
        """
        nodes are divided into k clusters, and each cluster is connected with probability p_in, and the probability of connecting to other clusters is p_out.
        """
        batch_matrices = []
        for i in range(batch_size):
            k_clusters = random.randint(2, k_max)
            break_points = sorted(random.sample(range(1, n), k_clusters-1))
            all_points = [0] + break_points + [n]
            sizes = [all_points[i+1] - all_points[i] for i in range(k_clusters)]
            probs = np.full((k_clusters, k_clusters), p_out)
            np.fill_diagonal(probs, p_in)
            G = nx.stochastic_block_model(sizes, probs)
            for u, v in G.edges:
                G[u][v]['weight'] = np.random.uniform(0, 1)
            F = nx.to_numpy_array(G)
            batch_matrices.append(F)
        F_batch = torch.from_numpy(np.array(batch_matrices)).float()
        return F_batch

